# mealdb_node_connector_config.yml
# Configuration for MealDBNodeConnector agent

mealdb_api:
  # Base URL for all MealDB API requests
  base_url: "https://www.themealdb.com/api/json/v1/1/"
  # Optional: Timeout in seconds for HTTP requests
  timeout: 15
  # Optional: Number of retries on network failure
  retry_count: 2
