# joke_api_node/config.yml
# Regular configuration for JokeApiNode
joke_api:
  endpoints:
    - url: "https://v2.jokeapi.dev/joke/Any?blacklistFlags=racist"
      description: "Get Jokes with Blacklist"
      request_type: "GET"
      request_parameter: "blacklistFlags=racist"
    - url: "https://v2.jokeapi.dev/joke/Any?lang=de"
      description: "Get Jokes (Language German)"
      request_type: "GET"
      request_parameter: "lang=de"
