# config.yml for CatImageFetcher
# Configuration file for cat_image_fetcher node

cat_api:
  # Base API endpoint for fetching cat images
  base_url: "https://api.thecatapi.com/v1/images/search"
  # Default number of cat images to fetch per request
  default_limit: 10
