# lunar_date_node.yml
# Configuration for LunarDateConversionNode
# All parameters non-sensitive (public API)

lunar_date_conversion:
  endpoint: "https://data.weather.gov.hk/weatherAPI/opendata/lunardate.php"
  request_type: "GET"
  default_date: "2024-08-08" # YYYY-MM-DD format; change as needed
  documentation_url: "https://data.gov.hk/en-data/dataset/hk-hko-rss-gregorian-lunar-calendar-conversion-table?ref=freepublicapis.com"
