# config.yml for HeatStressWarningNode
# This configuration contains operational parameters.

endpoints:
  english: "https://data.weather.gov.hk/weatherAPI/opendata/hsww.php?lang=en"
  traditional_chinese: "https://data.weather.gov.hk/weatherAPI/opendata/hsww.php?lang=tc"
  simplified_chinese: "https://data.weather.gov.hk/weatherAPI/opendata/hsww.php?lang=sc"
request_type: "GET"
# No sensitive information required for this node
