# starlink_tle_fetcher_config.yml
# Configuration for StarlinkTleFetcherNode

fetcher_config:
  endpoint: "https://celestrak.org/NORAD/elements/gp.php?INTDES=2020-025&FORMAT=JSON-PRETTY" # Celestrak Starlink TLE data endpoint
  request_type: "GET"
  timeout_seconds: 30 # reasonable default for API call
  description: "JSON format for all objects from Starlink launch with International Designator 2020-025"
  documentation_url: "https://celestrak.org/NORAD/documentation/gp-data-formats.php?ref=freepublicapis.com"
